export const AUTHORIZE_ACTION = 'AUTHORIZE_ACTION';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASS = 'UPDATE_PASS';
export const UPDATE_PASS_REPEAT = 'UPDATE_PASS_REPEAT';
export const CHANGE_DIALOG_STATE = 'CHANGE_DIALOG_STATE';
