export const CHANGE_LOADER_STATUS = 'CHANGE_LOADER_STATUS';
export const CHANGE_QUIT_DIALOG_STATUS = 'CHANGE_QUIT_DIALOG_STATUS';
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
export const CHANGE_DIALOG_STATE = 'CHANGE_DIALOG_STATE';
